# Site
name: 'kanoki'
description: 'Transforming World with Data'
favicon: 'images/author/favicon.jpg'
baseurl: ''
disqus: 'demowebsite'
email: 'wowthemesnet@gmail.com'
banner_image : 'images/kanoki.jpg'

include: ["_pages"]
permalink: /:year/:month/:day/:title/
search: false # true or false for serach
google_analytics: "UA-102260785-1"
google_ad_client : "ca-pub-1898260049766578"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag


# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post

  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page

# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 9

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
